// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package metric

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Start                int64             `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64             `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	TimeoutMinutes       int64             `protobuf:"varint,4,opt,name=timeoutMinutes,proto3" json:"timeoutMinutes,omitempty"`
	Source               string            `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Description          string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	RemediationAction    string            `protobuf:"bytes,7,opt,name=remediationAction,proto3" json:"remediationAction,omitempty"`
	Title                string            `protobuf:"bytes,11,opt,name=title,proto3" json:"title,omitempty"`
	Properties           map[string]string `protobuf:"bytes,20,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Event) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Event) GetTimeoutMinutes() int64 {
	if m != nil {
		return m.TimeoutMinutes
	}
	return 0
}

func (m *Event) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetRemediationAction() string {
	if m != nil {
		return m.RemediationAction
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "metric.Event")
	proto.RegisterMapType((map[string]string)(nil), "metric.Event.PropertiesEntry")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x49, 0x62, 0x22, 0x37, 0x01, 0xff, 0x2c, 0x87, 0x2c, 0x82, 0x10, 0x2c, 0x24, 0x85,
	0xa4, 0xd0, 0x46, 0x84, 0x2b, 0x2c, 0xae, 0x14, 0x24, 0xdf, 0x20, 0x26, 0x53, 0x0c, 0x5e, 0x76,
	0xc3, 0xec, 0xe4, 0xe0, 0x3e, 0xa7, 0x5f, 0x48, 0x76, 0x22, 0x72, 0x9c, 0xdd, 0xbc, 0xf7, 0x7b,
	0xcb, 0xec, 0x3c, 0x28, 0x71, 0x8f, 0x4e, 0x9a, 0x89, 0xbd, 0x78, 0x53, 0x8c, 0x28, 0x4c, 0xfd,
	0xfd, 0x77, 0x0a, 0xf9, 0x36, 0xfa, 0x66, 0x0d, 0x79, 0x90, 0x8e, 0xc5, 0xa6, 0x55, 0x52, 0x67,
	0xed, 0x22, 0xcc, 0x15, 0x64, 0xe8, 0x06, 0x9b, 0xa9, 0x17, 0x47, 0xf3, 0x00, 0x17, 0x42, 0x23,
	0xfa, 0x59, 0xde, 0xc9, 0xcd, 0x82, 0xc1, 0x9e, 0x29, 0x3c, 0x71, 0xcd, 0x0d, 0x14, 0xc1, 0xcf,
	0xdc, 0xa3, 0xcd, 0xab, 0xa4, 0x5e, 0xb5, 0xbf, 0xca, 0x54, 0x50, 0x0e, 0x18, 0x7a, 0xa6, 0x49,
	0xc8, 0x3b, 0x5b, 0x28, 0x3c, 0xb6, 0xcc, 0x23, 0x5c, 0x33, 0x8e, 0x38, 0x50, 0x17, 0xe5, 0x5b,
	0xaf, 0xb9, 0x73, 0xcd, 0xfd, 0x07, 0xf1, 0xdf, 0x42, 0xb2, 0x43, 0x5b, 0x6a, 0x62, 0x11, 0x66,
	0x03, 0x30, 0xb1, 0x9f, 0x90, 0x85, 0x30, 0xd8, 0x75, 0x95, 0xd5, 0xe5, 0xd3, 0x5d, 0xb3, 0x1c,
	0xdd, 0xe8, 0xc1, 0xcd, 0xc7, 0x1f, 0xdf, 0x3a, 0xe1, 0x43, 0x7b, 0xf4, 0xe0, 0x76, 0x03, 0x97,
	0x27, 0x38, 0x36, 0xf1, 0x85, 0x07, 0x9b, 0xe8, 0x96, 0x38, 0xc6, 0xcd, 0xfb, 0x6e, 0x37, 0xa3,
	0x36, 0xb6, 0x6a, 0x17, 0xf1, 0x9a, 0xbe, 0x24, 0x9f, 0x85, 0x96, 0xfc, 0xfc, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x5d, 0x3c, 0x85, 0x77, 0x73, 0x01, 0x00, 0x00,
}
