// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gauge.proto

package metric

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gauge struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Value                int64             `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Unit                 string            `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Properties           map[string]string `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Gauge) Reset()         { *m = Gauge{} }
func (m *Gauge) String() string { return proto.CompactTextString(m) }
func (*Gauge) ProtoMessage()    {}
func (*Gauge) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5dfbbc861401b2, []int{0}
}

func (m *Gauge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gauge.Unmarshal(m, b)
}
func (m *Gauge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gauge.Marshal(b, m, deterministic)
}
func (m *Gauge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gauge.Merge(m, src)
}
func (m *Gauge) XXX_Size() int {
	return xxx_messageInfo_Gauge.Size(m)
}
func (m *Gauge) XXX_DiscardUnknown() {
	xxx_messageInfo_Gauge.DiscardUnknown(m)
}

var xxx_messageInfo_Gauge proto.InternalMessageInfo

func (m *Gauge) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Gauge) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Gauge) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Gauge) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Gauge) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterType((*Gauge)(nil), "metric.Gauge")
	proto.RegisterMapType((map[string]string)(nil), "metric.Gauge.PropertiesEntry")
}

func init() { proto.RegisterFile("gauge.proto", fileDescriptor_8a5dfbbc861401b2) }

var fileDescriptor_8a5dfbbc861401b2 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4f, 0x2c, 0x4d,
	0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x4d, 0x2d, 0x29, 0xca, 0x4c, 0x56,
	0x7a, 0xca, 0xc8, 0xc5, 0xea, 0x0e, 0x12, 0x17, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x14, 0xb8, 0xb8, 0x53, 0x52, 0x8b, 0x93,
	0x8b, 0x32, 0x0b, 0x4a, 0x32, 0xf3, 0xf3, 0x24, 0x98, 0xc0, 0x52, 0xc8, 0x42, 0x42, 0x22, 0x5c,
	0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x10, 0x0e, 0xc8,
	0xac, 0xd2, 0xbc, 0xcc, 0x12, 0x09, 0x16, 0x88, 0x59, 0x20, 0xb6, 0x90, 0x2d, 0x17, 0x57, 0x41,
	0x51, 0x7e, 0x41, 0x6a, 0x51, 0x49, 0x66, 0x6a, 0xb1, 0x04, 0xab, 0x02, 0xb3, 0x06, 0xb7, 0x91,
	0xac, 0x1e, 0xc4, 0x19, 0x7a, 0x60, 0x27, 0xe8, 0x05, 0xc0, 0xe5, 0x5d, 0xf3, 0x4a, 0x8a, 0x2a,
	0x83, 0x90, 0x34, 0x48, 0xd9, 0x72, 0xf1, 0xa3, 0x49, 0x0b, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56,
	0x42, 0x1d, 0x0c, 0x62, 0x22, 0x5c, 0x03, 0x71, 0x29, 0x84, 0x63, 0xc5, 0x64, 0xc1, 0x98, 0xc4,
	0x06, 0xf6, 0xb6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x0e, 0xc9, 0x97, 0x05, 0x01, 0x00,
	0x00,
}
