version: "3.5"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://${DOCKER_HOST_IP}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "test:1:1"

  consumer:
    depends_on:
      - kafka
    container_name: consumer
    build:
      context: ./consumer/examples/consumer
      dockerfile: Dockerfile
      args:
        NETRC_LOCAL: ${NETRC_LOCAL}
        KAFKA_SERVER: ${DOCKER_HOST_IP}:9094
        KAFKA_TOPIC: test

  producer:
    depends_on:
      - kafka
    container_name: producer
    build:
      context: ./producer/examples/timed_producer
      dockerfile: Dockerfile
      args:
        NETRC_LOCAL: ${NETRC_LOCAL}
        KAFKA_SERVER: ${DOCKER_HOST_IP}:9094
        KAFKA_TOPIC: test
